source "https://rubygems.org"

ruby '2.7.1'

gem "sinatra", "~>2.2.0"
gem "sinatra-contrib"
gem "erubis"
gem "redcarpet"
gem "bcrypt"

gem 'minitest'
gem 'rack-test'

group :production do
  gem "puma"
end